#!/bin/sh /etc/rc.common
START=98
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/python3 /data/ai_cpe/mqtt_bridge.py daemon
    procd_set_param env HOME=/data/hermes/home
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn
    procd_close_instance
}
