#!/bin/sh /etc/rc.common
START=98
USE_PROCD=1

PROG=/data/ai_cpe/sherpa-onnx/bin/sherpa-onnx-offline-websocket-server
GLIBC=/data/ai_cpe/glibc/ld-linux-aarch64.so.1
LIBP=/data/ai_cpe/glibc
MODEL=/data/ai_cpe/sherpa-onnx/paraformer-zh-small/model.int8.onnx
TOKENS=/data/ai_cpe/sherpa-onnx/paraformer-zh-small/tokens.txt

start_service() {
	procd_open_instance
	procd_set_param command $GLIBC --library-path $LIBP $PROG --port=6006 --num-work-threads=2 --num-threads=2 --model-type=paraformer --tokens=$TOKENS --paraformer=$MODEL
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
}
